name: hyper_storage_shared_preferences
description: A backend for hyper_storage using shared_preferences for Flutter applications.

version: 0.1.0

repository: https://github.com/hyper-designed/hyper_storage
homepage: https://github.com/hyper-designed/hyper_storage/tree/main/packages/hyper_storage_shared_preferences

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ">=2.5.4 <3.0.0"
  hyper_storage: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
  test: ^1.29.0

resolution: workspace